baseURL = "https://my-blog-c5a.pages.dev/"
locale = "zh-cn"
title = "misaka10030"
theme = "PaperMod"
[params]
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "你好，我是misaka10030"
  Content = "这里是我的个人博客"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/misakamikoto-art"

[[params.socialIcons]]
  name = "email"
  url = "mailto:3656885944@qq.com"
